// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc5004.gravLoop_2014;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetraindriveLeft;
    public static SpeedController drivetraindriveRight;
    public static DoubleSolenoid clampCPiston;
    public static SpeedController elbowMotor;
    public static SpeedController flippermotorL;
    public static DigitalInput flipperswitchL;
    public static DigitalInput flipperswtchR;
    public static Solenoid rampRPiston;
    public static Compressor pneumaticPumpCompressor1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetraindriveLeft = new Victor(1);
	LiveWindow.addActuator("Drivetrain", "driveLeft", (Victor) drivetraindriveLeft);
        
        drivetraindriveRight = new Victor(2);
	LiveWindow.addActuator("Drivetrain", "driveRight", (Victor) drivetraindriveRight);
        
        clampCPiston = new DoubleSolenoid(1, 2, 3);      
             
        elbowMotor = new Victor(3);
	LiveWindow.addActuator("elbow", "elbowMotor", (Victor) elbowMotor);//*/
        
//        flippermotorL = new Victor(1, 4);
//	LiveWindow.addActuator("flipper", "motorL", (Victor) flippermotorL);
        
        flipperswitchL = new DigitalInput(1, 4);
	LiveWindow.addSensor("flipper", "switchL", flipperswitchL);
        
        flipperswtchR = new DigitalInput(1, 3);
	LiveWindow.addSensor("flipper", "swtchR", flipperswtchR);
       
        rampRPiston = new Solenoid(1, 7);
	LiveWindow.addActuator("Ramp", "RPiston", rampRPiston);
        
        pneumaticPumpCompressor1 = new Compressor(1, 1, 1, 1);
        
        pneumaticPumpCompressor1.start();
	
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
